version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  fileTest-docker:
    docker:
      - image: circleci/node

    steps:
      - checkout
      - run:
          name: instalando dependencias_
          working_directory: node/
          command: npm install
      - run:
          name: realizando test
          working_directory: node/
          command: npm test
workflows:
  main:
    jobs:
      - fileTest-docker